#!/bin/bash

TEXTDOMAINDIR=/opt/lights-on/locale
TEXTDOMAIN=lights-on

if pgrep -x lightsOn.sh > /dev/null; then
notify-send -i preferences-desktop-screensaver-symbolic "Lights On" $"Already running"
else
(/opt/lights-on/lightsOn.sh &)
notify-send -i preferences-desktop-screensaver-symbolic "Lights On" $"Started"
fi
exit 0
