#!/bin/bash

TEXTDOMAINDIR=/opt/lights-on/locale
TEXTDOMAIN=lights-on

if pgrep -x lightsOn.sh > /dev/null; then
pkill lightsOn.sh
notify-send -i preferences-desktop-screensaver-symbolic "Lights On" $"Stopped"
else
notify-send -i preferences-desktop-screensaver-symbolic "Lights On" $"Already not running"
fi
exit 0
